#!/bin/sh
# Runs as part of the nginx docker-entrypoint.d/ sequence (before nginx starts).
# Injects runtime environment variables into a JS config file served to the browser.
set -e

CONFIG_FILE="/usr/share/nginx/html/config.js"

cat > "${CONFIG_FILE}" <<EOCONF
// Runtime configuration — generated at container startup from environment variables.
// DO NOT edit this file manually; it is overwritten on every container start.
window.CONFIG = {
    apiKey: "${API_KEY:-dev-api-key}"
};
EOCONF

echo "[nginx-entrypoint] Generated ${CONFIG_FILE}"
