{{- if .Values.redis.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-redis
  labels:
    app.kubernetes.io/name: stt-pipeline
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/component: redis
    app.kubernetes.io/managed-by: {{ .Release.Service }}
spec:
  type: {{ .Values.redis.service.type }}
  ports:
    - port: {{ .Values.redis.service.port }}
      targetPort: tcp-redis
      protocol: TCP
      name: tcp-redis
  selector:
    app.kubernetes.io/name: stt-pipeline
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/component: redis
{{- end }}
