apiVersion: v1
kind: Secret
metadata:
  name: {{ .Release.Name }}-secret
  labels:
    app.kubernetes.io/name: stt-pipeline
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
type: Opaque
data:
  POSTGRES_USER: {{ .Values.secrets.postgres.user | b64enc | quote }}
  POSTGRES_PASSWORD: {{ .Values.secrets.postgres.password | b64enc | quote }}
  POSTGRES_DB: {{ .Values.secrets.postgres.db | b64enc | quote }}
  MINIO_ACCESS_KEY: {{ .Values.secrets.minio.accessKey | b64enc | quote }}
  MINIO_SECRET_KEY: {{ .Values.secrets.minio.secretKey | b64enc | quote }}
  API_KEY: {{ .Values.secrets.api.apiKey | b64enc | quote }}
  HF_TOKEN: {{ .Values.secrets.worker.hfToken | b64enc | quote }}
